"""Public schema package grouped into RAG, agent, and operational models."""
from .agents import (
    AgentInfo,
    AgentListResponse,
    AskRequest,
    AskResponse,
    ChatTurn,
    FoundryAvailability,
    HostedAgent,
    PersonaSummary,
    Usage,
)
from .documents import DocumentExtractionResponse
from .sessions import (
    MemoryContextInfo,
    SessionCreate,
    SessionDetail,
    SessionMessage,
    SessionSummary,
)
from .ops import (
    AzureDeployment,
    AzureDeployments,
    AzureStatus,
    Health,
    ScrapeRequest,
    ScrapeResponse,
    SpeakRequest,
    TranscribeResponse,
)
from .rag import (
    ChunkInfo,
    ChunkRequest,
    ChunkResponse,
    CollectionInfo,
    IngestRequest,
    IngestResponse,
    SearchHit,
    SearchRequest,
    SearchResponse,
    Strategy,
)
from .tooling import (
    ToolCatalogItem,
    ToolCatalogResponse,
    ToolSelectionRequest,
    ToolSelectionResponse,
)

__all__ = [
    "AgentInfo",
    "AgentListResponse",
    "AskRequest",
    "AskResponse",
    "AzureDeployment",
    "AzureDeployments",
    "AzureStatus",
    "ChunkInfo",
    "ChunkRequest",
    "ChunkResponse",
    "ChatTurn",
    "CollectionInfo",
    "DocumentExtractionResponse",
    "FoundryAvailability",
    "Health",
    "HostedAgent",
    "IngestRequest",
    "IngestResponse",
    "MemoryContextInfo",
    "PersonaSummary",
    "ScrapeRequest",
    "ScrapeResponse",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "SessionCreate",
    "SessionDetail",
    "SessionMessage",
    "SessionSummary",
    "SpeakRequest",
    "Strategy",
    "TranscribeResponse",
    "ToolCatalogItem",
    "ToolCatalogResponse",
    "ToolSelectionRequest",
    "ToolSelectionResponse",
    "Usage",
]
