"""Public schema package grouped into RAG, agent, and operational models."""
from .agents import (
    AgentInfo,
    AgentListResponse,
    AskRequest,
    AskResponse,
    FoundryAvailability,
    HostedAgent,
    PersonaSummary,
    Usage,
)
from .ops import (
    AzureDeployment,
    AzureDeployments,
    AzureStatus,
    Health,
    ScrapeRequest,
    ScrapeResponse,
    SpeakRequest,
    TranscribeResponse,
)
from .rag import (
    ChunkInfo,
    ChunkRequest,
    ChunkResponse,
    CollectionInfo,
    IngestRequest,
    IngestResponse,
    SearchHit,
    SearchRequest,
    SearchResponse,
    Strategy,
)

__all__ = [
    "AgentInfo",
    "AgentListResponse",
    "AskRequest",
    "AskResponse",
    "AzureDeployment",
    "AzureDeployments",
    "AzureStatus",
    "ChunkInfo",
    "ChunkRequest",
    "ChunkResponse",
    "CollectionInfo",
    "FoundryAvailability",
    "Health",
    "HostedAgent",
    "IngestRequest",
    "IngestResponse",
    "PersonaSummary",
    "ScrapeRequest",
    "ScrapeResponse",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "SpeakRequest",
    "Strategy",
    "TranscribeResponse",
    "Usage",
]
