name: frontend-admin

services:
  admin:
    build:
      context: ..
      dockerfile: docker/frontend-admin.Dockerfile
    container_name: libra-frontend-admin
    ports:
      - "7800:7800"
    environment:
      BACKEND_URL: http://host.docker.internal:7799
    volumes:
      - ../app:/srv/app
      - ../static:/srv/static
      - ../templates:/srv/templates
    extra_hosts:
      - "host.docker.internal:host-gateway"
